// Raw publications data preloaded from fitradeoff.org/publications
const RAW_PUBLICATIONS_DATA = `
Journals
1. About the method
- [Pessoa, M. E. B. T., Frej, E. A., & de Almeida, A. T. (2025). A novel information-driven approach for selecting a project portfolio: a benefit-to-cost based method combining decomposition and holistic elicitation paradigms. Omega, 103456.](https://www.sciencedirect.com/science/article/pii/S0305048325001823)
- [de Almeida, A.T., Frej, E.A., de Almeida, J.A. et al. Multicriteria Group Decision-Making using Flexible and Interactive Tradeoff with Partial Preference Information. Group Decis Negot (2025). https://doi.org/10.1007/s10726-025-09926-z](https://link.springer.com/article/10.1007/s10726-025-09926-z)
- [de Araújo, Y.P.G., Frej, E.A., Roselli, L.R.P. et al. A partial information-based preference elicitation procedure for intracriteria evaluation in multicriteria additive models. OPSEARCH (2025). https://doi.org/10.1007/s12597-025-00926-w](https://link.springer.com/article/10.1007/s12597-025-00926-w#citeas)
- [Ribeiro, M. L. S., Vasconcelos, T. R. S., Frej, E. A., De Almeida, A. T. (2024). EFFECTS OF HOLISTIC EVALUATIONS ON FITRADEOFF METHOD USING A SIMULATION STUDY, Pesquisa Operacional, 44.](https://www.scielo.br/j/pope/a/8YcNP9n6SQg6qDb8FTWn6yG/)
- [de Almeida, J. A. A., Frej, E.A. & Roselli, L.R.P., de Almeida, A.T. 2024. Analytical aspects of combining holistic evaluation and decomposition elicitation for preference modeling in the FITradeoff method. International Transactions in Operational Research. 1-42. http://doi.org/10.1111/itor.13470.](https://onlinelibrary.wiley.com/doi/10.1111/itor.13470)
- [DE ALMEIDA AT, FREJ EA, ROSELLI LRP & COSTA APCS. 2023. A summary on FITradeoff method with methodological and practical developments and future perspectives. Pesquisa Operacional, 43:e268356. doi: 10.1590/0101-7438.2023.043spe1.00268356.](https://www.scielo.br/j/pope/a/PRp4yxfFmKKZWd77yhsbv5f/?format=pdf&lang=em)
- [Marques, A. C., Frej, E. A., & de Almeida, A. T. (2022). Multicriteria decision support for project portfolio selection with the FITradeoff method. Omega, 111, 102661.](https://www.sciencedirect.com/science/article/pii/S0305048322000688)
- [de Almeida, A.T., Frej, E.A. & Roselli, L.R.P. Combining holistic and decomposition paradigms in preference modeling with the flexibility of FITradeoff. Cent Eur J Oper Res 29, 7–47 (2021).](https://link.springer.com/article/10.1007/s10100-020-00728-z#citeas)
- [Frej, E. A., Ekel, P., & de Almeida, A. T. (2021) A benefit-to-cost ratio based approach for portfolio selection under multiple criteria with incomplete preference information. Information Sciences, 545, 487-498.](https://www.sciencedirect.com/science/article/pii/S0020025520308859)
- [Kang, T. H. A., Frej, E. A., & de Almeida, A. T. (2020). Flexible and Interactive Tradeoff Elicitation for Multicriteria Sorting Problems. Asia-Pacific Journal of Operational Research, 37(05), 2050020.](https://www.worldscientific.com/doi/abs/10.1142/S0217595920500207)
- [Mendes, J. A. J., Frej, E. A., Almeida, A. T. D., & Almeida, J. A. D. (2020). EVALUATION OF FLEXIBLE AND INTERACTIVE TRADEOFF METHOD BASED ON NUMERICAL SIMULATION EXPERIMENTS. Pesquisa Operacional, 40.](https://www.scielo.br/scielo.php?pid=S0101-74382020000100208&script=sci_arttext)
- [Frej, Eduarda Asfora ; de Almeida, Adiel Teixeira ; COSTA, Ana Paula Cabral Seixas . Using data visualization for ranking alternatives with partial information and interactive tradeoff elicitation. Operational Research, v. 19, p. 1-22, 2019](http://dx.doi.org/10.1007/s12351-018-00444-2)
- [de Almeida-Filho, A.T., de Almeida, A.T., Costa, A.P.C.S. A flexible elicitation procedure for additive model scale constants (2017) Annals of Operations Research, 259 (1-2), pp. 65-83](https://link.springer.com/article/10.1007/s10479-017-2519-y)
- [de Almeida, A. T.; de Almeida, J. A. ; COSTA, A. P. C. S. ; de Almeida-Filho, A. T. “A New Method for Elicitation of Criteria Weights in Additive Models: Flexible and Interactive Tradeoff”, European Journal of Operational Research, v. 250, p. 179-191, 2016.](http://www.sciencedirect.com/science/article/pii/S0377221715008140)

2. Behavioral studies
- [Barbosa Ferreira, E., Rani Soares de Vasconcelos, T., Reis Peixoto Roselli, L., & Teixeira de Almeida, A. (2025). Rebuilding a DSS with feedback from behavioral and neuroscience studies. International Transactions in Operational Research.](https://onlinelibrary.wiley.com/doi/full/10.1111/itor.13614)
- [Carneiro de Lima da Silva, A. L., Cabral Seixas Costa, A. P., & de Almeida, A. T. (2022). Analysis of the cognitive aspects of the preference elicitation process in the compensatory context: a neuroscience experiment with FITradeoff. International Transactions in Operational Research.](https://onlinelibrary.wiley.com/doi/full/10.1111/itor.13210)
- [Roselli, L. R. P., & de Almeida, A. T. (2022). Use of the Alpha-Theta Diagram as a decision neuroscience tool for analyzing holistic evaluation in decision making. Annals of Operations Research, 1-23.](https://link.springer.com/article/10.1007/s10479-021-04495-1)
- [Roselli, Lucia Reis Peixoto ; ALMEIDA, ADIEL TEIXEIRA . The use of the success-based decision rule to support the holistic evaluation process in FITradeoff. International Transactions in Operational Research, v. 28, p. itor.12958, 2021.](https://onlinelibrary.wiley.com/doi/abs/10.1111/itor.12958)
- [Costa, A. P. C. S., & de Almeida, A. T. (2021). Exploring cognitive aspects of FITradeoff method using neuroscience tools. Annals of Operations Research, 1-23.](https://link.springer.com/article/10.1007/s10479-020-03894-0)
- [Roselli, L. R. P., Pereira, L. D. S., da Silva, A. L. C. D. L., de Almeida, A. T., Morais, D. C., & Costa, A. P. C. S. (2020). Neuroscience experiment applied to investigate decision-maker behavior in the tradeoff elicitation procedure. Annals of Operations Research, 289(1), 67-84.](https://link.springer.com/article/10.1007/s10479-019-03394-w)
- [Roselli, Lucia Reis Peixoto ; de Almeida, Adiel Teixeira ; Frej, Eduarda Asfora . Decision neuroscience for improving data visualization of decision support in the FITradeoff method. Operational Research, v. 19, p. 1-21, 2019](http://dx.doi.org/10.1007/s12351-018-00445-1)

3. Applications
- [Monteiro do Nascimento, F. A., Neto, G. D. M. P., Hazin Alencar, L., & Valdes-Vasquez, R. (2026). Multicriteria subcontractor selection model for construction activities in wind farm projects. International Journal of Construction Management, 26(5), 772-788.](https://www.tandfonline.com/doi/abs/10.1080/15623599.2025.2535748)
- [De Medeiros, J. C. G., Gaudêncio, M. P., Bittencourt, M. L., Kramer, R., & Alencar, L. H. (2026). Selecting subcontractors and scheduling activities in civil construction projects: an integrated approach using FITradeoff and Genetic Algorithm. Expert Systems with Applications, 132509.](https://www.sciencedirect.com/science/article/pii/S0957417426014223)
- [Costa, J. C. de O. R., & Silva, M. M. (2025). Prioritizing Public Policies to Combat Violence Against Women: A Multicriteria Decision Analysis. Violence Against Women, 0(0).](https://journals.sagepub.com/doi/full/10.1177/10778012251347605)
- [Ferreira, D. V., de Oliveira, V., Ferreira, T. V., & de Gusmão, A. P. H. (2025). Decision model for selecting a portfolio of non-technical loss mitigation projects for power distribution systems. Utilities Policy, 95, 101967.](https://www.sciencedirect.com/science/article/pii/S0957178725000827)
- [Ferreira, E. B., de Lima, R. V. B., da Silva, A. L. C. D. L., & Roselli, L. R. P. (2025). Benefit-to-cost analysis in a portfolio problem for the context of the construction sector: a multi-criteria approach. Engineering, Construction and Architectural Management, 1-23. https://doi.org/10.1108/ECAM-01-2025-0148](https://www.emerald.com/ecam/article/doi/10.1108/ECAM-01-2025-0148/1275433)
- [dos Santos Júnior, A. E., & Cardoso, P. S. M. (2025). Applying the FITradeoff method for software prioritization. Gest. prod, 32, e5724.](https://www.researchgate.net/profile/Gestao-Producao/publication/390370862_Applying_the_FITradeoff_method_for_software_prioritization_Aplicacao_do_metodo_FITradeoff_para_priorizacao_de_software/links/67ebf2c749e91c0fead1f039/Applying-the-FITradeoff-method-for-software-prioritization-Aplicacao-do-metodo-FITradeoff-para-priorizacao-de-software.pdf)
- [da Silva, A. B., Marques, A. B., da Costa Junior, J. F., & de Souza, R. P. (2025). Multicriteria decision model for ranking the performance of remote work activities: Case study in a call center company in Brazil. WORK, 10519815251320037.](https://journals.sagepub.com/doi/abs/10.1177/10519815251320037)
- [da Cunha, C. P. C. B., de Miranda Mota, C. M., Frej, E. A., Roselli, L. R. P., & de Almeida, A. T. (2024). Setting priorities for police operations by using a multicriteria decision approach with partial information. IMA Journal of Management Mathematics, dpae030.](https://academic.oup.com/imaman/advance-article-abstract/doi/10.1093/imaman/dpae030/7863370)
- [Ribeiro, M. L. S., Roselli, L. R. P., Ferreira, R. J. P., & Almeida, A. T. D. (2024). A MANUFACTURING STRATEGY APPROACH FOR SOLVING AGGREGATE PRODUCTION PLANNING PROBLEMS WITH MULTIPLE OBJECTIVES. Pesquisa Operacional, 44, e284932.](https://www.scielo.br/j/pope/a/tHrCxgG9nwPjcLSKKrZZ6QS/)
- [Oliveira, T. E. S. D., Pessôa, L. A. M., Frej, E. A., & Souza, A. C. D. (2024). A COMBINATION OF FITRADEOFF AND COGNITIVE MAPS FOR OBJECT DEFINITION IN PUBLIC PROCUREMENT. Pesquisa Operacional, 44, e273855.](https://www.scielo.br/j/pope/a/TdpD3CLDbRksh9ZgLmkhBJC/)
- [De Medeiros, MG; Cavalcante, RJL; De Lima da Silva, ALC; Roselli, LRP (2024). A multicriteria model for ranking logistics startups during the acquisition process in a transport company. International Transactions in Operational Research. 1-19. http://doi.org/10.1111/itor.13536](https://onlinelibrary.wiley.com/doi/10.1111/itor.13536)
- [Corrêa, T. L., & Morais, D. C. (2024). Private Partner Prioritization for Public–Private Partnership Contracts in a Brazilian Water Company Using a Multi-Criteria Decision Aid Method. Mathematics, 12(13), 2041.](https://www.mdpi.com/2227-7390/12/13/2041)
- [Frej, E. A., De Almeida, A. T. (2024). BUILDING A MULTICRITERIA DECISION MODEL FOR SOLVING A TECHNICAL SCHOOL LOCATION PROBLEM WITH THE FITRADEOFF METHOD, Pesquisa Operacional, 44.](https://www.scielo.br/j/pope/a/L84D7XPfZvsPyz5h7TMVj4g/?format=pdf&lang=en)
- [Silva, ECS; Morais, DC (2024). Prioritization of alternatives in waste management: A case in Pernambuco state, Brazil. Pesquisa Operacional, 44: e281064. https://doi.org/10.1590/0101-7438.2023.043.00281064.](https://www.scielo.br/j/pope/a/4wcpQ3JZzWfwddn4MkxH47K/?lang=en)
- [Ferreira, D., de Gusmão, A. P. H., & de Almeida, J. A. (2024). A multicriteria model for assessing maturity in industry 4.0 context. Journal of Industrial Information Integration, 100579.](https://www.sciencedirect.com/science/article/abs/pii/S2452414X24000232)
- [Vieira Dantas, N., Henriques de Gusmão, A. P., & Teixeira Gonzaga, M. (2023). A multicriteria model to support decisions regarding data protection compliance. Journal of Decision Systems, 1-17.](https://www.tandfonline.com/doi/full/10.1080/12460125.2023.2263683)
- [Causil, OMM; Morais, DC (2023). Multicriteria negotiation model for selecting sustainable suppliers’ problem in the agribusiness. Pesquisa Operacional, 33: e20220090. https://doi.org/10.1590/0103-6513.20220090.](https://www.scielo.br/j/prod/a/HjYr9rKNs6yVR8jwTGj58Jn/?lang=en)
- [SCHRAMM VB, DAMASCENO AC & SCHRAMM F. 2023. Supporting the Choice of the BestFit Agile Model Using FITradeoff. Pesquisa Operacional, 43 (spe1): e264750. doi: 10.1590/0101-7438.2023.043spe1.00264750.](https://www.scielo.br/j/pope/a/bnydnjKwSBRBNPc7d6FMfyy/?format=pdf&lang=em)
- [ZANAZZI JF, ZANAZZI JL & PONTELLI D. 2023. Prioritization Of Improvement Actions In Industrial Production: Application Of The Fitradeoff Method To Order Improvement Actions Identified Through The Failures Modes And Effects Analysis (FMEA). Pesquisa Operacional, 43(spe1): e263696. doi: 10.1590/0101-7438.2023.043spe1.00263696.](https://www.scielo.br/j/pope/a/tWCSdps5kp5b6SZx4Cn8vyk/?format=pdf&lang=em)
- [CARVALHO RCLC, ROSELLI LRP & FIGUEIRA JR. 2023. Assigning priorities for raw material of a large pet food producer in the context of supply disruption. Pesquisa Operacional, 43 (spe1): e263605. doi: 10.1590/0101-7438.2023.043spe1.00263605.](https://www.scielo.br/j/pope/a/zhf86rqcmXFsYYN54PvvrKR/?format=pdf&lang=em)
- [CYRENO MW AND ROSELLI JLRPR. 2023. Application of the FITradeoff Method in a Portfolio Problem in the Context of Reverse Logistics for Wholesale. Pesquisa Operacional, 43 (spe1): e263604. doi:10.1590/0101-7438.2023.043spe1.00263604](https://www.scielo.br/j/pope/a/7yzHYf7m8hMz4SwTdD8JYXS/?format=pdf&lang=em)
- [RICO LUGO SD, DU B, ALMEIDA JA & NISHINO N. 2023. A Circular Food Economy Multicriteria Decision Problem Based on the Fitradeoff Method. Pesquisa Operacional, 43(spe1): e263528. doi:10.1590/0101-7438.2023.043spe1.00263528.](https://www.scielo.br/j/pope/a/C8GHbzhbSd8DPBjBJMptHDL/?format=pdf&lang=em)
- [RODRÍGUEZ, J. M. M.; FREJ, E. A.; KANG, T. H. A.; DE ALMEIDA, A. T. 2023. Outsourcing laboratory services from a Colombian agricultural research company using the FITradeoff method under multiple stakeholders analysis. Pesquisa Operacional, 43 (spe1): e258518. doi: 10.1590/0101-7438.2023.043spe1.00258518](https://www.scielo.br/j/pope/a/67mbsvvmkFQ3PvYrMxyLSsJ/?format=pdf&lang=en)
- [CZEKAJSKI M, WACHOWICZ T & FREJ EA. 2023. Exploring the combination of holistic evaluation and elicitation by decomposition in FITradeoff: prioritizing cultural tourism products in Poland. Pesquisa Operacional, 43 (spe1): e263454. doi: 10.1590/0101-7438.2023.043spe1.00263454](https://www.scielo.br/j/pope/a/8xHDr9JfL3VDQwzqWq43gQr/?format=pdf&lang=em)
- [OLIVEIRA RSM, MORAIS DC & SIEBERT J. 2023. Developing and Evaluating New Alternatives for Urban Mobility: a Case Study of a Brazilian City. Pesquisa Operacional, 43(spe1): e263440. doi: 10.1590/0101-7438.2023.043spe1.00263440.](https://www.scielo.br/j/pope/a/crBGwpPdddmmrs4MD8DzdcQ/?format=pdf&lang=em)
- [SANTOS AG, PESSOA LAMP, MOTA CMM AND FREJ EA. 2023. A fitradeoff-based approach for strategic decisions on military budget. Pesquisa Operacional, 43 (spe1): e262789. doi: 10.1590/0101-7438.2023.043spe1.00262789.](https://www.scielo.br/j/pope/a/qBzTQQkNWmhz9SBKnyKjCHg/?format=pdf&lang=em)
- [de Assis, A.G., dos Santos, A.F.A., dos Santos, L.A. et al. Classification of medicines and materials in hospital inventory management: a multi-criteria analysis. BMC Med Inform Decis Mak 22, 325 (2022). https://doi.org/10.1186/s12911-022-02069-0](https://link.springer.com/article/10.1186/s12911-022-02069-0)
- [Sarmento dos Santos-Neto, J. B. & Costa, A. P. (2023). A Multi-Criteria Decision-Making Model for Selecting a Maturity Model. International Journal of Decision Support System Technology (IJDSST), 15(1), 1-15. http://doi.org/10.4018/IJDSST.319305](https://www.igi-global.com/article/a-multi-criteria-decision-making-model-for-selecting-a-maturity-model/319305)
- [Causil, O. M. M., & Morais, D. C. (2023). Food supplier sorting model for strategic supply chain sustainable development. Business Strategy and the Environment, 1– 16. https://doi.org/10.1002/bse.3356](https://onlinelibrary.wiley.com/doi/abs/10.1002/bse.3356)
- [Rodrigues, A.J.d.S., Cavalcante, C.A.V. and Alberti, A.R. (2023), A multicriteria model to support the selection of inspection service providers based on the delay time model. Intl. Trans. in Op. Res.. https://doi.org/10.1111/itor.13274](https://onlinelibrary.wiley.com/doi/abs/10.1111/itor.13274)
- [Pessoa, M. E. B. T., Roselli, L. R. P., & de Almeida, A. T. (2022). Using the FITradeoff Decision Support System to Support a Brazilian Compliance Organization Program. Information Systems Frontiers, 1-16.](https://link.springer.com/article/10.1007/s10796-022-10290-5)
- [Oliveira, A. C. D., Silva, W. D. O., & Morais, D. C. (2022). Developing and prioritizing lean key performance indicators for plastering supply chains. Production, 32.](https://www.scielo.br/j/prod/a/86sp4n7WM6yjhyKJyrS56QP/)
- [dos Santos, L.A., dos Santos, A.F.A., de Assis, A.G. et al. Model to support intervention prioritization for the control of Aedes aegypti in Brazil: a multi-criteria approach. BMC Public Health 22, 932 (2022). https://doi.org/10.1186/s12889-022-13006-1](https://bmcpublichealth.biomedcentral.com/articles/10.1186/s12889-022-13006-1)
- [FREJ, E. A.; MORAIS, D. C.; ALMEIDA, A. T. de. Negotiation Support Through Interactive Dominance Relationship Specification. Group Decision And Negotiation, [S.L.], 13 out. 2021. Springer Science and Business Media LLC. http://dx.doi.org/10.1007/s10726-021-09761-y.](https://link.springer.com/article/10.1007/s10726-021-09761-y)
- [De Morais Correia, L. M. A., da Silva, J. M. N., dos Santos Leite, W. K., Lucas, R. E. C., & Colaço, G. A. (2021). A multicriteria decision model to rank workstations in a footwear industry based on a FITradeoff-ranking method for ergonomics interventions. Operational Research. doi:10.1007/s12351-021-00671-0](https://link.springer.com/article/10.1007/s12351-021-00671-0) 
- [Shukla, S., & Dubey, A. (2021). Celebrity selection in social media ecosystems: a flexible and interactive framework. Journal of Research in Interactive Marketing.](https://www.emerald.com/insight/content/doi/10.1108/JRIM-04-2020-0074/full/html)
- [Sousa Ribeiro, M. L., Peixoto Roselli, L. R., Asfora Frej, E., Teixeira de Almeida, A., & Costa Morais, D. (2021). Using the FITradeoff method to solve a shopping mall location problem in the northeastern countryside of Brazil. Control & Cybernetics, 50(1).](https://yadda.icm.edu.pl/baztech/element/bwmeta1.element.baztech-86bb688f-993f-4a8c-8fa4-b20f9f9436e9)
- [Frazão, T. D., Dos Santos, A. F., Camilo, D. G., da Costa Júnior, J. F., & de Souza, R. P. (2021). Priority setting in the Brazilian emergency medical service: a multi-criteria decision analysis (MCDA). BMC medical informatics and decision making, 21(1), 1-16.](https://bmcmedinformdecismak.biomedcentral.com/articles/10.1186/s12911-021-01503-z)
- [Fernandes, C. H. D. A., Guarnieri, P., & Vieira, B. D. O. (2021). Multicriteria Model Proposition to Support the Management of Systems of E-Waste Collection. Logistics, 5(3), 60.](https://www.mdpi.com/2305-6290/5/3/60)
- [de Lacerda, N. L. B., dos Santos-Neto, J. B. S., & Martins, C. L. (2021). MCDM Model for Natural Gas Pressure Reducing Station Site Selection. International Journal of Decision Support System Technology (IJDSST), 13(1), 67-84.](https://www.igi-global.com/article/mcdm-model-for-natural-gas-pressure-reducing-station-site-selection/267160)
- [RODRIGUEZ, JENNY MILENA MORENO ; KANG, TAKANNI HANNAKA ABREU ; FREJ, EDUARDA ASFORA; DE ALMEIDA, ADIEL TEIXEIRA. Decision-making in the purchase of equipment in agricultural research laboratories: a multiple-criteria approach under partial information. Decision Science Letters, v. 10, p. 451-462, 2021.](http://www.growingscience.com/dsl/Vol10/dsl_2021_28.pdf)
- [da Silva Monte, M. B., & Morais, D. C. (2019). A decision model for identifying and solving problems in an urban water supply system. Water Resources Management, 33(14), 4835-4848.](https://link.springer.com/article/10.1007/s11269-019-02401-w)
- [Kang, T. H. A., Soares Júnior, A. M. C., de Almeida, A. T. Evaluating electric power generation technologies: A multicriteria analysis based on the FITradeoff method, Energy (2018)](https://doi.org/10.1016/j.energy.2018.09.165)
- [P. A. Alvarez Carrillo, L. R. P. Roselli, E. A. Frej and A. T. de Almeida, Selecting an agricultural technology package based on the flexible and interactive tradeoff method, Annals of Operations Research (2018).](http://doi.org/10.1007/s10479-018-3020-y)
- [de Macedo, P.P., Mota, C.M.D.M., Sola, A.V.H. Meeting the Brazilian Energy Efficiency Law: A flexible and interactive multicriteria proposal to replace non-efficient motors (2018) Sustainable Cities and Society, 41, pp. 822-832](https://www.sciencedirect.com/science/article/pii/S2210670717314427)
- [Frej, Eduarda Asfora ; Roselli, Lucia Reis Peixoto ; ARAÚJO DE ALMEIDA, JÔNATAS ; de Almeida, Adiel Teixeira . A Multicriteria Decision Model for Supplier Selection in a Food Industry Based on FITradeoff Method. MATHEMATICAL PROBLEMS IN ENGINEERING, v. 2017, p. 1-9](http://dx.doi.org/10.1155/2017/4541914)
- [Gusmão. A.P.H.; Medeiros, C. P. “A Model for Selecting a Strategic Information System Using the FITradeoff” Mathematical Problems in Engineering, vol. 2016, Article ID 7850960, 7 pages, 2016. doi:10.1155/2016/7850960](https://www.hindawi.com/journals/mpe/2016/7850960/)

Technological products
1. de ALMEIDA, A. T. ; de ALMEIDA, A. T. ; Almeida, J. A ; FREJ, E. A. ; MEDEIROS, C. P. ; KRYM, E. M. FITradeoff for choice problematic (FU-T1ENO-CF3E). 2016. Computer program. Register number: BR512016001325-7, date of register: 08/11/2016. Instituição de registro: INPI – Instituto Nacional da Propriedade Industrial. 
2. de ALMEIDA, A. T. ; FREJ, E. A. ; ALMEIDA, J. A. ; MEDEIROS, C. P. ; KRYM, E. M. ; VILACA, I. ; RIBEIRO, M. . FITradeoff for ranking problematic (FU-T1ONO-LF1). 2020. Computer program. Register number (INPI): BR512020002174-3, date of register: 20/10/2020. Instituição de registro: INPI – Instituto Nacional da Propriedade Industrial.

Books and Book chapters
1. About the method
- [Santo, P. P. P. D. E., Frej, E. A., & Almeida, A. T. D. (2021, December). Improving the Elicitation Process for Intra-criterion Evaluation in the FITradeoff Method. In Innovation for Systems Information and Decision Meeting (pp. 68-86). Springer, Cham.](https://link.springer.com/chapter/10.1007/978-3-030-91768-5_5)
- [Vieira, M. J. L., Frej, E. A., Almeida, A. T. D., & Viana, F. F. C. L. (2021, December). Incorporating Hierarchical Criteria Structure in the Fitradeoff Method. In Innovation for Systems Information and Decision Meeting (pp. 100-118). Springer, Cham.](https://link.springer.com/chapter/10.1007/978-3-030-91768-5_7)

2. Applications
- [Frej, EA; Da Silva, GS; Da Silva, ML; Morais, DC (2024). Negotiation Platform for Supporting Multi-issue Bilateral Negotiations: The Case of an Offshore Wind Energy Company and a Fishing Community in the Northeast of Brazil. In International Conference on Group Decision and Negotiation, vol 509 (pp. 117-129). Springer, Cham.](https://link.springer.com/chapter/10.1007/978-3-031-59373-4_10)
- [da Silva, G.M., Frej, E.A., de Almeida, A.T. (2023). Ranking Potential Investors Using the FITradeoff Method and Value Focused Thinking in a Group Decision Problem. In: Maemura, Y., Horita, M., Fang, L., Zaraté, P. (eds) Group Decision and Negotiation in the Era of Multimodal Interactions. GDN 2023. Lecture Notes in Business Information Processing, vol 478. Springer, Cham.](https://doi.org/10.1007/978-3-031-33780-2_3)
- [Dell’Ovo, M., Oppio, A., Frej, E.A., de Almeida, A.T. (2023). Supporting the Resources Allocation for Inner Areas by the Use of the FITradeoff Method. In: Gervasi, O., et al. Computational Science and Its Applications – ICCSA 2023 Workshops. ICCSA 2023. Lecture Notes in Computer Science, vol 14108.](https://doi.org/10.1007/978-3-031-37117-2_28)
- [de Lacerda, M.M., Cardoso, M.M. (2023). Improvement of Personnel Support to the Armed Forces Military Using Fitradeoff Method. In: Deschamps, F., Pinheiro de Lima, E., Gouvêa da Costa, S.E., G. Trentin, M. (eds) Proceedings of the 11th International Conference on Production Research – Americas. ICPR 2022. Springer, Cham.](https://doi.org/10.1007/978-3-031-36121-0_39)
- [Ferreira, D.V., de Gusmão, A.P.H. (2022). Maturity Assessment in the Context of Industry 4.0 – an Application Using FITradeoff Method in a Textile Industry. In: Cabral Seixas Costa, A.P., Papathanasiou, J., Jayawickrama, U., Kamissoko, D. (eds) Decision Support Systems XII: Decision Support Addressing Modern Industry, Business, and Societal Needs. ICDSST 2022. Lecture Notes in Business Information Processing, vol 447. Springer, Cham.](https://link.springer.com/chapter/10.1007/978-3-031-06530-9_12#citeas)
- [Cyreno, M.W., Roselli, L.R.P., de Almeida, A.T. (2022). Using the FITradeoff Method for Solving a Truck Acquisition Problem at a Midsize Carrier. In: Cabral Seixas Costa, A.P., Papathanasiou, J., Jayawickrama, U., Kamissoko, D. (eds) Decision Support Systems XII: Decision Support Addressing Modern Industry, Business, and Societal Needs. ICDSST 2022. Lecture Notes in Business Information Processing, vol 447. Springer, Cham.](https://link.springer.com/chapter/10.1007/978-3-031-06530-9_11#citeas)
- [de Morais Correia, L.M.A., Frej, E.A., Ribeiro, M.L.S., Morais, D.C. (2022). Eliciting Preferences with Partial Information in Multi-issue Negotiations: An Analysis of the FITradeoff-Based Negotiation Protocol. In: Morais, D.C., Fang, L. (eds) Group Decision and Negotiation: Methodological and Practical Issues. GDN 2022. Lecture Notes in Business Information Processing, vol 454. Springer, Cham.](https://link.springer.com/chapter/10.1007/978-3-031-07996-2_2#citeas)
- [Morais, D. C., Araújo, A. M., Frej, E. A., & Almeida, A. T. D. (2022). Group Decision Process for Evaluating a Mango Variety to Be Planted in New Agricultural Farms. In Collective Decisions: Theory, Algorithms And Decision Support Systems (pp. 247-264). Springer, Cham.](https://link.springer.com/chapter/10.1007/978-3-030-84997-9_11)
- [Oppio, A., Dell’Ovo, M., & Capolongo, S. (2020). Decision Support System for the Location of Healthcare Facilities: SitHealth Evaluation Tool. Springer Nature.](https://www.springer.com/gp/book/9783030501723)
- [Frej, Eduarda Asfora; de Almeida, Adiel Teixeira ; ROSELLI, LUCIA REIS PEIXOTO . Solving Multicriteria Group Decision-Making (MCGDM) Problems Based on Ranking with Partial Information. Lecture Notes in Business Information Processing. 1ed.: Springer International Publishing, 2019, v. , p. 3-16.](https://link.springer.com/chapter/10.1007/978-3-030-21711-2_1)
- [Frej E.A., de Almeida A.T., Morais, D C. (2019) “Using FITradeoff for supporting a decision process of a multicriteria decision problem”. In: Huber, Sandra, Geiger, Martin Josef, de Almeida, Adiel Teixeira (Eds.) “Multiple Criteria Decision Making and Aiding – Cases on Models and Methods with Computer Implementations”. 2019. Vol 274, Springer International Series in Operations Research & Management Science.](https://www.springer.com/gp/book/9783319993034)
- [Dell’Ovo M., Frej E.A., Oppio A., Capolongo S., Morais D.C., de Almeida A.T. (2018) FITradeoff Method for the Location of Healthcare Facilities Based on Multiple Stakeholders’ Preferences. In: Chen Y., Kersten G., Vetschera R., Xu H. (eds) Group Decision and Negotiation in an Uncertain World. GDN 2018. Lecture Notes in Business Information Processing, vol 315. Springer, Cham. DOI 10.1007/978-3-319-92874-6_8](http://www.doi.org/10.1007/978-3-319-92874-6_8)
- [Dell’Ovo, M., Frej, E. A., Oppio, A., Capolongo, S., Morais, D.C., de Almeida, A.T.: Multicriteria Decision Making for Healthcare Facilities Location with Visualization Based on FITradeoff Method. In: Linden, I., Liu, C., Colot, C. Decision Support Systems VII. LNBIP 282, pp pp. 32–44, (2017). DOI 10.1007/978-3-319-57487-5_3](https://doi.org/10.1007/978-3-319-57487-5_3)
- [de Almeida, A T; Almeida J A ; Costa, A. P. C. S. ; Almeida Filho, A. T. de “A DSS for Resolving Evaluation of Criteria by Interactive Flexible Elicitation Procedure”. In: DARGAM F; HERNÁNDEZ JE; ZARATÉ P; LIU S; RIBEIRO R; DELIBASIC B; PAPATHANASIOU J.. (Org.). Decision Support Systems III – Impact of Decision Support Systems for Global Environments, LNBIP 184. 1ed.: Springer, 2014, v. 184, p. 157-166. DOI 10.1007/978-3-319-11364-7_14](https://doi.org/10.1007/978-3-319-11364-7_14)

3. Behavioral studies
- [De Vasconcelos, TRS; Roselli, LRP; De Almeida, AT (2024). Performance of Holistic Evaluation for Multi-criteria Decisions Comparing Selection or Elimination of Alternatives. In: International Conference on Decision Support System Technology, vol 506 (pp. 85-97). Springer, Cham.](https://link.springer.com/chapter/10.1007/978-3-031-59376-5_7)
- [Roselli, L. R. P., & de Almeida, A. T. (2023, June). FITradeoff Decision Support System Applied to Solve a Supplier Selection Problem. In International Conference on Information and Knowledge Systems (pp. 49-62). Cham: Springer Nature Switzerland.](https://link.springer.com/chapter/10.1007/978-3-031-51664-1_4)
- [Ferreira, E. B., de Vasconcelos, T. R. S., Roselli, L. R. P., & de Almeida, A. T. (2023, May). Behavioral Studies for the Use of Visualization in Holistic Evaluation for Multicriteria Decision Problems Decision. In International Conference on Decision Support System Technology (pp. 265-276). Cham: Springer Nature Switzerland.](https://link.springer.com/chapter/10.1007/978-3-031-32534-2_19)
- [Roselli, L.R.P., de Almeida, A.T. (2022). Neuroscience Behavioral Studies for Modulation of the FITradeoff Method. In: Morais, D.C., Fang, L. (eds) Group Decision and Negotiation: Methodological and Practical Issues. GDN 2022. Lecture Notes in Business Information Processing, vol 454. Springer, Cham.](https://link.springer.com/chapter/10.1007/978-3-031-07996-2_4#citeas)
- [Roselli, L. R. P., de Almeida, A.T. (2020) Analysis of Graphical Visualizations for Multi-criteria Decision Making in FITradeoff Method Using a Decision Neuroscience Experiment. In: Moreno-Jiménez J., Linden I., Dargam F., Jayawickrama U. (eds) Decision Support Systems X: Cognitive Decision Support Systems and Technologies. ICDSST 2020. Lecture Notes in Business Information Processing, vol 384. Springer, Cham.](https://link.springer.com/chapter/10.1007/978-3-030-46224-6_3)
- [de Almeida, A.T., Roselli, L.R.P. (2020) NeuroIS to Improve the FITradeoff Decision-Making Process and Decision Support System. In: Davis F.D., Riedl R., vom Brocke J., Léger PM., Randolph A.B., Fischer T. (eds) Information Systems and Neuroscience. NeuroIS 2020. Lecture Notes in Information Systems and Organisation, vol 43. Springer, Cham.](https://link.springer.com/chapter/10.1007/978-3-030-60073-0_13)
- [Roselli, L.R.P., de Almeida, A.T. (2020) Improvements in the FITradeoff Decision Support System for Ranking Order Problematic Based in a Behavioral Study with NeuroIS Tools. In: Davis F.D., Riedl R., vom Brocke J., Léger PM., Randolph A.B., Fischer T. (eds) Information Systems and Neuroscience. NeuroIS 2020. Lecture Notes in Information Systems and Organisation, vol 43. Springer, Cham.](https://link.springer.com/chapter/10.1007/978-3-030-60073-0_14)
- de Almeida, A.T., Roselli, L.R.P., Morais, D.C., Costa, A.P.C.S. (2020) Neuroscience Tools for Group Decision and Negotiation. In: Kilgour D.M., Eden C. (eds) Handbook of Group Decision and Negotiation. Springer, Cham.
- [da Silva, A.L.C.L., Costa, A.P.C.S. (2020) FITradeoff Decision Support System: An Exploratory Study with Neuroscience Tools. In: Davis F., Riedl R., vom Brocke J., Léger PM., Randolph A., Fischer T. (eds) Information Systems and Neuroscience. Lecture Notes in Information Systems and Organisation, vol 32. Springer, Cham.](https://link.springer.com/chapter/10.1007/978-3-030-28144-1_40)
- [Roselli L.R.P., Frej E.A., de Almeida A.T. (2018) Neuroscience Experiment for Graphical Visualization in the FITradeoff Decision Support System. In: Chen Y., Kersten G., Vetschera R., Xu H. (eds) Group Decision and Negotiation in an Uncertain World. GDN 2018. Lecture Notes in Business Information Processing, vol 315. Springer, Cham. DOI 10.1007/978-3-319-92874-6_5](http://www.doi.org/10.1007/978-3-319-92874-6_5)
- [de Almeida, A.T., Roselli, L.R.P.: Visualization for decision support in FITradeoff method: exploring its evaluation with cognitive neuroscience. In: Linden, I., Liu, C., Colot, C. Decision Support Systems VII. Data, Information and Knowledge Visualization in Decision Support Systems. LNBIP 282, pp pp. 61–73, (2017) doi: 10.1007/978-3-319-57487-5_5](https://www.doi.org/10.1007/978-3-319-57487-5_5)

Other conference communications
- Czekajski, M., Wachowicz, T., & Frej, E. A. (2021, December). FITradeoff Based Analysis of Cultural Tourism Products Regarding Post-industrial Heritage in Czeladź Commune in Poland. In Innovation for Systems Information and Decision Meeting (pp. 1-19). Springer, Cham.
- Da Silva, C. E. B., Ferreira, R. J. P., & Daher, S. D. F. D. (2021, October). Multicriteria Model for Key Performance Indicators Selection Applied in a Transportation Company. In 2021 IEEE International Conference on Systems, Man, and Cybernetics (SMC) (pp. 2227-2231). IEEE.
- Mondadori, J. A., Belderrain, M. C. N., Ferreira, R. J. P., & Françozo, R. V. (2021, December). Manufacturing Execution System Selection by Use of Multicriteria Partial Information Method. In Innovation for Systems Information and Decision Meeting (pp. 87-99). Springer, Cham.
- Roselli, L. R. P., & Almeida, A. T. D. (2021, May). Using FITradeoff Method for Supply Selection with Decomposition and Holistic Evaluations for Preference Modelling. In International Conference on Decision Support System Technology (pp. 18-29). Springer, Cham.
- Neto, G. P., Alencar, L. H., Rabbani, E. K., & Valdes-Vasquez, R. (2021, December). An Analysis of Social Sustainability Indicators Using FITradeoff Multicriteria Decision Method. In 2021 IEEE International Conference on Industrial Engineering and Engineering Management (IEEM) (pp. 457-461). IEEE.
- Silva, W. D. O., & Morais, D. C. (2021, October). A Group Decision Support System to Share Responsibilities Towards a Circular Economy Transition for Solid Waste Management in Developing Countries. In 2021 IEEE International Conference on Systems, Man, and Cybernetics (SMC) (pp. 2221-2226). IEEE.
- Cunha, C. P. C. B. D., Miranda Mota, C. M. D., Almeida, A. T. D., Frej, E. A., & Roselli, L. R. P. (2020, December). Applying the FITradeoff method for aiding prioritization of special operations of Brazilian federal police. In Innovation for Systems Information and Decision Meeting (pp. 110-125). Springer, Cham.
- e Silva, L. C., Daher, S. D. F. D., Santiago, K. T. M., & Costa, A. P. C. S. (2019, October). Selection of an Integrated Security Area for locating a State Military Police Station based on MCDM/A method. In 2019 IEEE International Conference on Systems, Man and Cybernetics (SMC) (pp. 1530-1534). IEEE.
- Silva, M. M., de Gusmão, A. P. H., de Andrade, C. T. A., & Silva, W. (2019, October). The integration of VFT and FITradeoff multicriteria method for the selection of WCM projects. In 2019 IEEE International Conference on Systems, Man and Cybernetics (SMC) (pp. 1513-1517). IEEE.
- FREJ, E. A.; MORAIS, D. C. ; de ALMEIDA, A. T. ; Kersten, G. E. . Partial information for eliciting negotiators? preferences during the offer exchanging process. In: 19th International Conference on Group Decision and Negotiation in 2019 a Joint GDN-EWG/BOR meeting, 2019, Loughborough.
- Cunha, C. P. ; Mota, C. M. ; de Almeida, Adiel Teixeira ; FREJ, E. A. . Building a Multicriteria Decision Making Model for Prioritizing Brazilian Federal Police Activities. In: INFORMS Annual Meeting, 2019, Seattle.
- Frej, Eduarda Asfora; de Almeida, Adiel Teixeira . Solving Multicriteria Ranking Problems Based on Partial Information with FITradeoff Method. In: INFORMS Annual Meeting, 2019, Seattle.
- de Almeida, Adiel Teixeira ; FREJ, E. A. ; ROSELLI, L. R. P. . Multicriteria Group Decision Making (MCGDM) Processes with Flexible and Interactive Tradeoff Elicitation. In: INFORMS Annual Meeting, 2019, Seattle.
- FREJ, E. A.; Morais, Danielle Costa ; de Almeida, Adiel Teixeira ; Kersten, G. E. . Assessing Negotiators’ Preferences with Partial Information and Flexible Elicitation. In: INFORMS Annual Meeting, 2019, Seattle.
- Cunha, C. P. ; Mota, C. M. ; de ALMEIDA, A. T. ; FREJ, E. A. . Applying VFT and Fitradeoff for Multicriteria Group Decision Making in the Context of Brazilian Federal Police Operational Activities. In: INFORMS Annual Meeting, 2019, Seattle.
- de Almeida, Adiel Teixeira ; FREJ, E. A. . Preference Modeling for Multi-criteria Group Decision Making/aiding with FITradeoff Method. In: 2018 INFORMS International Conference, 2018, Taipei.
- Rodriguez, J. M. M., Kang, T. H. A., Frej, E. A., & Almeida, A. T. D. (2018, May). A Group Decision-Making Model for Supplier Selection: The Case of a Colombian Agricultural Research Company. In International Conference on Decision Support System Technology (pp. 132-141). Springer, Cham.
- FREJ, E. A.; de ALMEIDA, A. T. . Flexible and Interactive DSS for Ranking Problematic. In: 21st Conference of the International Federation of Operational Research Societies – IFORS, 2017, Quebec City.
- Frej, Eduarda Asfora; de Almeida, Adiel Teixeira . Ranking Alternatives With Partial Information Based On Flexible Interactive Tradeoff. In: 2017 INFORMS Annual Meeting, 2017, Houston.
- de Almeida, Adiel Teixeira ; FREJ, E. A. . Multicriteria group decision using FITradeoff for Preference Elicitation. In: INFORMS Annual Meeting, 2017, 2017, Houston.
- de ALMEIDA, A. T. ; Frej, Eduarda Asfora ; FERREIRA, R. J. P. . Decision Aid with Partial Information Using FITradeoff for Preference Elicitation. In: 21st Conference of the International Federation of Operational Research Societies, 2017, Quebec City.
- KANG, T. H. A.; RODRIGUEZ, J. M. M. ; ALMEIDA, A. T. . Supplier Selection Using FITradeoff Method: an Application in Laboratories for Agricultural Research. In: 24th International Conference on Multiple Criteria Decision Making, 2017, Ottawa.
- AIDAR, G. G. O. ; Ferreira, R. J. P. ; KANG, T. H. A. ; de Almeida, A. T. . ANÁLISE DE LOCALIZAÇÃO DE UMA EMPRESA DE SERVIÇOS: UMA PROPOSTA BASEADA NO MÉTODO FITRADEOFF. In: XXXVII ENCONTRO NACIONAL DE ENGENHARIA DE PRODUCAO, 2017, Joinvile-SC.
- Dell Ovo, Marta ; FREJ, E. A. ; Oppio, Alessandra ; Capolongo, Stefano ; Morais, Danielle Costa ; de Almeida, Adiel Teixeira . Assessing stakeholders preferences about Healthcare Facility Location using FITradeoff method. In: 17th International Conference on Group Decision and Negotiation, 2017, Stuttgart.
- ROSELLI, L. R. P. ; Frej, Eduarda Asfora ; de Almeida, Adiel Teixeira . Designing Preference Modeling for FITradeoff Method with Decision Neuroscience Experiments. In: 17th International Conference on Group Decision and Negotiation, 2017, Stuttgart.
- FREJ, E. A.; de ALMEIDA, A. T. . Multicriteria Group Decision Model for Supplier Selection in a Food Industry. In: Internation Conference on Group Decision and Negotiation – GDN, 2016, 2016, Bellingham.
- Lugo, S.D.R. ; de Almeida, A T . FITradeoff multicriteria method for a flexible and interactive preference elicitation in small company decision problem. CLAIO XVIII 2016 Conference, Santiago.
- Pessoa, L A M; Ferreira R J P; de Almeida, A T; Almeida Filho, A T “A Navy Weapon Selection Throughout Fitradeoff”, INFORMS Annual Meeting, Nashvile, USA, 2016
- Neto, L. G. C. L. Aplicação do método multicritério FITradeoff para escolha de usina sucroalcooleira para suprimento de cana-de-açúcar, XXXVI ENEGEP – Encontro Nacional de Engenharia de Produção 2016
- Ferreira, R. J. P.; de Almeida, A. T. Construindo modelos de apoio à decisão nas organizações e o método FITradeoff, XXXVI ENEGEP (Encontro Nacional de Engenharia de Produção), João Pessoa, Brasil, 2016
- Ferreira, R. J. P.; de Almeida, A. T. Construindo modelos de apoio à decisão nas organizações e o método FITradeoff, XXIX ENDIO and XXVII EPIO, Buenos Aires, Argentina, 2016
- de Almeida, A T; Almeida J A ; Costa, A. P. C. S. ; Almeida Filho, A. T. de Flexible And Interactive Tradeoff Elicitation Procedure, INFORMS Annual Meeting, Philadelphia, USA, 2015
- de Almeida, A T; Almeida J A ; Costa, A. P. C. S. ; Almeida Filho, A. T. de . Flexible Elicitation procedure for Additive Models, 23rd International Conference on Multiple Criteria Decision Making, Hamburg, Germany, 2015
- de Almeida, A T; Almeida J A ; Costa, A. P. C. S. ; Almeida Filho, A. T. de . A DSS for Resolving Evaluation of Criteria by Interactive Flexible Elicitation on supplier selection problems, 20th Conference of the International Federation of Operational Research Societies (IFORS), Barcelona, Spain, 2014
- de Almeida, A T; Almeida J A ; Costa, A. P. C. S. ; Almeida Filho, A. T. de . Resolving Evaluation of Criteria Weights by Interactive Flexible Elicitation, INFORMS Annual Meeting, San Francisco, USA, 2014
`;
